version: '2'
services:
 php:
   container_name: php_c
   build: ./docker_data/php/
   volumes:
     - .:/app
   command: chown -R www-data:www-data /app
   command: echo "192.168.9.11 mysql.app.dev" >> /etc/hosts
   command: php-fpm --nodaemonize
   links:
     - redis
   #ports:
   #  - "9001:9001"
 nginx:
  build: ./docker_data/nginx
  container_name: nginx_c
  ports:
    - "80:80"
  volumes:
    - .:/app
  links:
    - php
    - redis
 redis:
   container_name: redis_c
   build: ./docker_data/redis/
   ports:
     - "6379:6379"