version: '2'
services:
 php:
   container_name: php_c
   build: ./docker_data/php/
   volumes:
     - ./app:/app
   command: chown -R www-data:www-data /app
   command: php-fpm --nodaemonize
 nginx:
  build: ./docker_data/nginx
  container_name: nginx_c
  ports:
    - "80:80"
  volumes:
    - ./app:/app
  links:
    - php